---
name: Build CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.RUNNER_PLATFORM }}
    strategy:
      matrix:
        version:
          - linux-amd64
          - macos-amd64
          - windows-amd64
            # XXX probably, 32 bit Windows is not so common, but still being
            # used.
            # https://github.com/LaserWeb/LaserWeb4/issues/592
          - windows-i386
        include:
          # XXX all of variables defined here are required. use empty string,
          # "", or `${{ false }}` for BUILD_DEPEND if you do not need. GitHub
          # Action will refuse to run the workflow if any of them are not
          # defined.
          #
          # OS: used in many `if:` and in artifact names to identify artifact.
          # ARCH: used in artifact names to identify artifact.
          # RUNNER_PLATFORM: used in `runs-on:` to choose platform of the
          # runner.
          # ELECTRON_BUILDER_FLAGS: extra flags to pass when building code
          # with electron-builder.
          # BUILD_DEPEND: space-separated list of package names to install
          # before the build
          # BUILD_ARTIFACT_FILE_EXT: file extension of artifacts. files with
          # this string at the end will be considered as artifacts.
          # PKG_INSTALL_CMD: command to install BUILD_DEPEND
          - version: linux-amd64
            OS: linux
            ARCH: amd64
            RUNNER_PLATFORM: ubuntu-latest
            ELECTRON_BUILDER_FLAGS: --linux AppImage --x64
            BUILD_DEPEND: graphicsmagick xz-utils
            PKG_INSTALL_CMD: sudo apt-get install
          - version: macos-amd64
            OS: macos
            ARCH: amd64
            RUNNER_PLATFORM: macos-latest
            ELECTRON_BUILDER_FLAGS: --macos
            BUILD_DEPEND: ${{ false }}
            PKG_INSTALL_CMD: brew install
          - version: windows-i386
            OS: windows
            ARCH: i386
            RUNNER_PLATFORM: windows-latest
            ELECTRON_BUILDER_FLAGS: --windows --ia32
            BUILD_DEPEND: ${{ false }}
            PKG_INSTALL_CMD: ""
          - version: windows-amd64
            OS: windows
            ARCH: amd64
            RUNNER_PLATFORM: windows-latest
            ELECTRON_BUILDER_FLAGS: --windows --x64
            BUILD_DEPEND: ${{ false }}
            PKG_INSTALL_CMD: ""
        node-version:
          # include 10.x only. serialport for 12.x is not available probably
          # because it does not support 12.x.
          #
          # "No prebuilt binaries found (target=12.18.1 runtime=node arch=x64 platform=linux)'
          - 10.x
    steps:
      - name: Install required packages
        if: matrix.BUILD_DEPEND
        run: ${{ matrix.PKG_INSTALL_CMD }} ${{ matrix.BUILD_DEPEND }}

      - name: Checkout lw.comm-server
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run yarn
        shell: bash
        run: |
          yarn --frozen-lockfile

      - name: Prepare
        shell: bash
        run: |
          yarn prep

      - name: Build lw.comm-server
        shell: bash
        run: |
          yarn build
